---
# testeado en redhat 8 OK
# Resumen de guia oficial https://docs.docker.com/engine/install/centos/
- hosts: all
  become: yes

  tasks:

    - name: Remueve paquetes antiguos 
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: Instala yum-utils, utilidad para manager repositorios
      yum:
        name: yum-utils
        state: latest

    - name: Instalando device-mapper-persistent-data
      yum:
        name: 
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Agregando repositorio 
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Instalando docker CE
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Iniciando servicio docker y habilitar el inicio
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Instalando docker-compose 
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Deshabilita selinux 
      selinux:
        state: disabled
   
       


